### ISSUE TITLE
lib crash ClassNotFoundException for org.pytorch.PyTorchAndroid

### ISSUE THREAD

**Issue by brunoalex** [erenalpaslan/removebg#13]
Im having Crash on some pixel devices that prevent me to upload to playstore 
Given the details you've provided, it appears that your Android app is encountering an ExceptionInInitializerError and a ClassNotFoundException for org.pytorch.PyTorchAndroid

have u seen this before? tks 

	at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(Unknown Source:139)
Exception java.lang.ExceptionInInitializerError:
  at org.pytorch.LiteModuleLoader.load (LiteModuleLoader.java)
  at com.kiltdesign.remove_background.MainActivity$RemoveBgViewModel.<init> (MainActivity.kt)
  at com.kiltdesign.remove_background.MainActivity$RemoveBgViewModelFactory.create (MainActivity.kt)
  at androidx.lifecycle.ViewModelProvider$Factory.create (ViewModelProvider.kt)
  at androidx.lifecycle.ViewModelProvider.get (ViewModelProvider.kt)
  at androidx.lifecycle.ViewModelProvider.get (ViewModelProvider.java)
  at com.kiltdesign.remove_background.MainActivity.ImageSelectorAndRemoveBg (MainActivity.kt)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt)
  at androidx.compose.material3.SurfaceKt$Surface$1.invoke (Surface.kt)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt)
  at androidx.compose.material3.SurfaceKt.Surface-T9BRK9s (Surface.kt)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt)
  at androidx.compose.material3.TextKt.ProvideTextStyle (Text.kt)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt)
  at androidx.compose.material3.MaterialThemeKt.MaterialTheme (MaterialTheme.kt)
  at com.kiltdesign.remove_background.ui.theme.ThemeKt.MyApplicationTheme (Theme.kt)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt)
  at androidx.compose.ui.platform.ComposeView.Content (ComposeView.android.kt)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt)
  at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals (CompositionLocals.kt)
  at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke (AndroidCompositionLocals.android.kt)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt)
  at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals (AndroidCompositionLocals.android.kt)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt)
  at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider (CompositionLocal.kt)
  at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke (ComposableLambda.jvm.kt)
  at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable (ActualJvm_jvm.kt)
  at androidx.compose.runtime.ComposerImpl.doCompose (Composer.kt)
  at androidx.compose.runtime.ComposerImpl.composeContent$runtime_release (Composer.kt)
  at androidx.compose.runtime.CompositionImpl.composeContent (Composition.kt)
  at androidx.compose.runtime.Recomposer.composeInitial$runtime_release (Recomposer.kt)
  at androidx.compose.runtime.CompositionImpl.composeInitial (Composition.kt)
  at androidx.compose.runtime.CompositionImpl.setContent (Composition.kt)
  at androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable (AndroidComposeView.android.kt)
  at androidx.compose.ui.platform.WrappedComposition.setContent (Wrapper.android.kt)
  at androidx.compose.ui.platform.WrappedComposition.onStateChanged (Wrapper.android.kt)
  at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent (LifecycleRegistry.kt)
  at androidx.lifecycle.LifecycleRegistry.addObserver (LifecycleRegistry.kt)
  at androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow (AndroidComposeView.android.kt)
  at android.view.View.dispatchAttachedToWindow (View.java:20753)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3490)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3497)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3497)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3497)
  at android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3497)
  at android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:2630)
  at android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:2143)
  at android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:8665)
  at android.view.Choreographer$CallbackRecord.run (Choreographer.java:1037)
  at android.view.Choreographer.doCallbacks (Choreographer.java:845)
  at android.view.Choreographer.doFrame (Choreographer.java:780)
  at android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:1022)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loopOnce (Looper.java:201)
  at android.os.Looper.loop (Looper.java:288)
  at android.app.ActivityThread.main (ActivityThread.java:7839)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:548)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1003)
Caused by java.lang.ClassNotFoundException: org.pytorch.PyTorchAndroid
  at java.lang.Runtime.nativeLoad
  at java.lang.Runtime.nativeLoad (Runtime.java:1121)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:1075)
  at java.lang.Runtime.loadLibrary0 (Runtime.java:998)
  at java.lang.System.loadLibrary (System.java:1656)
  at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary (NativeLoader.java)
  at org.pytorch.LiteNativePeer.<clinit> (LiteNativePeer.java)

**Comment by erenalpaslan** [comment]
Hi bruno, Are you using obfuscation in your app this can related with the pro-guard rules i will investigate it.

**Comment by MataMata11** [comment]
I have the same problem. Any updates? @erenalpaslan

**Comment by MataMata11** [comment]
I have it when use release build with:
isMinifyEnabled = true
isShrinkResources = true

**Comment by MataMata11** [comment]
my full error:

java.lang.ExceptionInInitializerError
                 	at org.pytorch.a.a(Unknown Source:2)
                 	at o2.b.<init>(Unknown Source:86)
                 	at b2.k.d(Unknown Source:277)
                 	at l2.a.k(Unknown Source:28)
                 	at N.c.k(Unknown Source:53)
                 	at A.H0.a(Unknown Source:204)
                 	at A.H0.k(Unknown Source:15)
                 	at N.c.k(Unknown Source:53)
                 	at q2.v.c(Unknown Source:151)
                 	at D.N.a(Unknown Source:98)
                 	at b2.k.c(Unknown Source:216)
                 	at k2.c.j(Unknown Source:36)
                 	at N.c.a(Unknown Source:45)
                 	at N.c.j(Unknown Source:8)
                 	at D.A.a(Unknown Source:160)
                 	at D.A.k(Unknown Source:27)
                 	at N.c.k(Unknown Source:53)
                 	at s.b.a(Unknown Source:182)
                 	at s.b.k(Unknown Source:43)
                 	at N.c.k(Unknown Source:53)
                 	at q2.v.u1(Unknown Source:14)
                 	at F.r.q(Unknown Source:117)
                 	at F.r.k(Unknown Source:10)
                 	at F.y.n(Unknown Source:33)
                 	at F.G0.a(Unknown Source:48)
                 	at F.o.a(Unknown Source:4)
                 	at F.y.o(Unknown Source:8)
                 	at i0.v.h(Unknown Source:29)
                 	at i0.v.g(Unknown Source:119)
                 	at i0.q.m(Unknown Source:180)
                 	at D.D.a(Unknown Source:890)
                 	at D.D.k(Unknown Source:11)
                 	at i0.s.a(Unknown Source:73)
                 	at k0.x.a(Unknown Source:41)
                 	at r.d.a(Unknown Source:50)
                 	at r.d.c(Unknown Source:1033)
                 	at H1.b.w(Unknown Source:59)
                 	at P.A.b(Unknown Source:47)
                 	at k0.n0.a(Unknown Source:154)
                 	at k0.M.h0(Unknown Source:108)
                 	at k0.M.a(Unknown Source:95)
                 	at u.q.a(Unknown Source:110)
                 	at k0.x.a(Unknown Source:41)
                 	at X.H.c(Unknown Source:0)
                 	at k0.C.a(Unknown Source:10)
                 	at X.H.c(Unknown Source:0)
                 	at k0.C.a(Unknown Source:10)
                 	at r.d.a(Unknown Source:50)
                 	at r.d.c(Unknown Source:1033)
                 	at H1.b.w(Unknown Source:59)
                 	at P.A.b(Unknown Source:47)
                 	at k0.n0.a(Unknown Source:154)
                 	at k0.M.h0(Unknown Source:108)
                 	at k0.M.a(Unknown Source:95)
                 	at u.q.a(Unknown Source:110)
                 	at k0.x.a(Unknown Source:41)
                 	at X.H.c(Unknown Source:0)
                 	at k0.C.a(Unknown Source:10)
                 	at X.H.c(Unknown Source:0)
                 	at k0.C.a(Unknown Source:10)
                 	at u.A.c(Unknown Source:96)
                 	at k0.C.a(Unknown Source:10)
                 	at r.d.a(Unknown Source:50)
                 	at r.d.c(Unknown Source:1033)
                 	at H1.b.w(Unknown Source:59)
                 	at P.A.b(Unknown Source:47)
                 	at k0.n0.a(Unknown Source:154)
                 	at k0.M.h0(Unknown Source:108)
                 	at k0.M.a(Unknown Source:95)
                 	at i0.I.a(Unknown Source:38)
                 	at k0.x.a(Unknown Source:41)
                 	at r.d.a(Unknown Source:50)
                 	at r.d.c(Unknown Source:1033)
                 	at H1.b.w(Unknown Source:59)
                 	at P.A.b(Unknown Source:47)
                 	at k0.n0.a(Unknown Source:154)
                 	at k0.M.h0(Unknown Source:108)
                 	at k0.V.c(Unknown Source:16)
                 	at k0.V.l(Unknown Source:17)
                 	at k0.V.i(Unknown Source:58)
                 	at l0.v.onMeasure(Unknown Source:82)
                 	at android.view.View.measure(View.java:26557)
                 	at l0.a.onMeasure(Unknown Source:66)
                 	at android.view.View.measure(View.java:26557)
                 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
                 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                 	at android.view.View.measure(View.java:26557)
                 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
                 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
                 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
                 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                 	at android.view.View.measure(View.java:26557)
                 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7022)
                 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:835)
                 	at android.view.View.measure(View.java:26557)
                 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4142)
                 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2836)
                 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3113)
                 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2543)
                 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9465)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
